import { useEffect, useState } from 'react';
import InterviewScoreCard from '../components/InterviewScoreCard';
import LoadingSpinner from '../components/LoadingSpinner';
import SectionCard from '../components/SectionCard';
import SimpleBarChart from '../components/SimpleBarChart';
import { getAnalytics } from '../services/analyticsService';

const AnalyticsPage = () => {
  const [analytics, setAnalytics] = useState(null); const [error, setError] = useState('');
  useEffect(() => { getAnalytics().then(({ analytics: data }) => setAnalytics(data)).catch((e) => setError(e.response?.data?.message || 'Unable to load analytics.')); }, []);
  if (!analytics) return error ? <p className="text-red-600">{error}</p> : <LoadingSpinner label="Calculating your analytics..." />;
  const interviewTrend = analytics.interviewTrend.map((item) => ({ label: new Date(item.date).toLocaleDateString(), score: item.score }));
  return <div className="mx-auto max-w-6xl space-y-7"><div><p className="text-sm font-semibold text-indigo-600 dark:text-indigo-400">Career analytics</p><h1 className="mt-1 text-3xl font-bold">See your developer growth clearly.</h1></div><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><InterviewScoreCard label="Career readiness" score={analytics.careerReadiness} /><InterviewScoreCard label="Roadmap progress" score={analytics.roadmapProgress} tone="emerald" /><SectionCard><p className="text-sm text-slate-500">Code analyses</p><p className="mt-2 text-3xl font-bold text-violet-600">{analytics.totalAnalyses}</p></SectionCard><SectionCard><p className="text-sm text-slate-500">Projects reviewed</p><p className="mt-2 text-3xl font-bold text-cyan-600">{analytics.totalProjectsReviewed}</p></SectionCard></section><section className="grid gap-6 lg:grid-cols-2"><SectionCard><h2 className="text-lg font-bold">Skills progress</h2><div className="mt-5"><SimpleBarChart data={analytics.skillsProgress.map((skill) => ({ label: skill.skillName, score: skill.level }))} labelKey="label" valueKey="score" /></div></SectionCard><SectionCard><h2 className="text-lg font-bold">Interview trend</h2><div className="mt-5"><SimpleBarChart data={interviewTrend} labelKey="label" valueKey="score" /></div></SectionCard></section><section className="grid gap-6 lg:grid-cols-2"><SectionCard><h2 className="text-lg font-bold">Strong skills</h2><div className="mt-4 flex flex-wrap gap-2">{analytics.strongSkills.length ? analytics.strongSkills.map((skill) => <span key={skill._id} className="rounded-full bg-emerald-100 px-3 py-1.5 text-sm font-semibold text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300">{skill.skillName} · {skill.level}%</span>) : <p className="text-sm text-slate-500">No strong skills yet.</p>}</div></SectionCard><SectionCard><h2 className="text-lg font-bold">Weak skills</h2><div className="mt-4 flex flex-wrap gap-2">{analytics.weakSkills.length ? analytics.weakSkills.map((skill) => <span key={skill._id} className="rounded-full bg-red-100 px-3 py-1.5 text-sm font-semibold text-red-700 dark:bg-red-500/10 dark:text-red-300">{skill.skillName} · {skill.level}%</span>) : <p className="text-sm text-slate-500">No weak skills identified.</p>}</div></SectionCard></section><SectionCard><h2 className="text-lg font-bold">Recent activities</h2><div className="mt-4 space-y-3">{analytics.recentActivities.length ? analytics.recentActivities.map((activity, index) => <div key={`${activity.type}-${index}`} className="flex justify-between gap-4 border-b border-slate-100 pb-3 text-sm last:border-0 dark:border-slate-800"><span>{activity.label}</span><span className="text-slate-500">{new Date(activity.date).toLocaleDateString()}</span></div>) : <p className="text-sm text-slate-500">Complete activities to see your progress timeline.</p>}</div></SectionCard></div>;
};

export default AnalyticsPage;
