import { useEffect, useState } from 'react';
import AnalysisLoading from '../components/AnalysisLoading';
import InterviewQuestionCard from '../components/InterviewQuestionCard';
import PrimaryButton from '../components/PrimaryButton';
import ProjectScoreCard from '../components/ProjectScoreCard';
import ReviewFeedbackCard from '../components/ReviewFeedbackCard';
import SectionCard from '../components/SectionCard';
import { getProjectReviewById, getProjectReviews, reviewProject } from '../services/projectReviewService';

const GITHUB_REPOSITORY_PATTERN = /^https:\/\/github\.com\/[^/\s]+\/[^/\s]+\/?$/i;

const GitHubReviewPage = () => {
  const [repositoryUrl, setRepositoryUrl] = useState(''); const [review, setReview] = useState(null); const [history, setHistory] = useState([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const loadHistory = async () => { try { const { reviews } = await getProjectReviews(); setHistory(reviews); } catch { /* History is supplementary. */ } };
  useEffect(() => { loadHistory(); }, []);
  const submit = async (event) => { event.preventDefault(); if (!GITHUB_REPOSITORY_PATTERN.test(repositoryUrl.trim())) return setError('Use a public URL such as https://github.com/owner/repository.'); setLoading(true); setError(''); try { const { review: result } = await reviewProject(repositoryUrl.trim()); setReview(result); await loadHistory(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to review this repository.'); } finally { setLoading(false); } };
  const openReview = async (reviewId) => { try { const { review: savedReview } = await getProjectReviewById(reviewId); setReview(savedReview); setRepositoryUrl(savedReview.repositoryUrl); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to open this review.'); } };
  return <div className="mx-auto max-w-7xl space-y-7"><div><p className="text-sm font-semibold text-indigo-600 dark:text-indigo-400">AI GitHub Project Review</p><h1 className="mt-1 text-3xl font-bold">Turn projects into portfolio evidence.</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Review a public GitHub repository for strengths, gaps, resume value, and interview readiness.</p></div><div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_280px]"><div className="space-y-5"><SectionCard><form onSubmit={submit} className="flex flex-col gap-3 sm:flex-row"><input value={repositoryUrl} onChange={(event) => setRepositoryUrl(event.target.value)} placeholder="https://github.com/owner/repository" className="min-w-0 flex-1 rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 dark:border-slate-700 dark:bg-slate-950" /><PrimaryButton type="submit" isLoading={loading}>Review project</PrimaryButton></form></SectionCard>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700 dark:bg-red-500/10 dark:text-red-300">{error}</p>}{loading && <AnalysisLoading />}{review && !loading && <div className="grid gap-5"><ProjectScoreCard score={review.score} repositoryName={review.repositoryName} /><SectionCard><h2 className="text-lg font-bold">Resume value</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{review.resumeValue}</p></SectionCard><div className="grid gap-5 lg:grid-cols-2"><ReviewFeedbackCard title="Strengths" items={review.strengths} tone="emerald" /><ReviewFeedbackCard title="Weaknesses" items={review.weaknesses} tone="red" /></div><ReviewFeedbackCard title="Suggested improvements" items={review.improvements} tone="indigo" /><InterviewQuestionCard questions={review.interviewQuestions} /></div>}</div><aside><SectionCard><h2 className="font-bold">Review history</h2><div className="mt-4 space-y-2">{history.length ? history.map((item) => <button key={item._id} type="button" onClick={() => openReview(item._id)} className="w-full rounded-lg border border-slate-200 p-3 text-left hover:border-indigo-400 dark:border-slate-700"><p className="font-semibold">{item.repositoryName}</p><p className="mt-1 text-sm text-indigo-600 dark:text-indigo-400">Score: {item.score}/100</p></button>) : <p className="text-sm text-slate-500">Your saved project reviews will appear here.</p>}</div></SectionCard></aside></div></div>;
};

export default GitHubReviewPage;
