import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { OnboardingProvider, useOnboarding } from '../context/OnboardingContext';
import { completeProfile, getProfile, updateProfile as updateProfileRequest } from '../services/profileService';
import { createSkill, getSkills } from '../services/skillService';
import Input from '../components/Input';
import PrimaryButton from '../components/PrimaryButton';
import ProgressBar from '../components/ProgressBar';
import SectionCard from '../components/SectionCard';
import SkillSelector from '../components/SkillSelector';

const titles = ['Personal details', 'Career goal', 'Skills selection', 'Learning preferences', 'Review & submit'];

const Wizard = () => {
  const navigate = useNavigate();
  const { profile, skills, updateProfile: updateDraft, setSkills } = useOnboarding();
  const [step, setStep] = useState(1); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { const hydrate = async () => { try { const [{ user }, { skills: savedSkills }] = await Promise.all([getProfile(), getSkills()]); if (user.profileCompleted) return navigate('/dashboard', { replace: true }); ['fullName', 'bio', 'college', 'graduationYear', 'targetRole', 'experienceLevel', 'preferredLearningStyle', 'dailyLearningGoal'].forEach((field) => { if (user[field] !== null && user[field] !== undefined) updateDraft(field, String(user[field])); }); setSkills(savedSkills); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to load onboarding data.'); } finally { setLoading(false); } }; hydrate(); }, []);
  const next = () => { setError(''); if (step === 1 && (!profile.fullName || !profile.bio || !profile.college || !profile.graduationYear)) return setError('Complete all personal details.'); if (step === 2 && !profile.targetRole) return setError('Enter your target role.'); if (step === 3 && !skills.length) return setError('Select at least one skill.'); setStep((value) => value + 1); };
  const submit = async () => { setSaving(true); setError(''); try { await updateProfileRequest({ ...profile, graduationYear: Number(profile.graduationYear), dailyLearningGoal: Number(profile.dailyLearningGoal) }); const { skills: savedSkills } = await getSkills(); const savedNames = new Set(savedSkills.map((skill) => skill.skillName)); await Promise.all(skills.filter((skill) => !savedNames.has(skill.skillName)).map(({ skillName, level, confidence }) => createSkill({ skillName, level, confidence }))); await completeProfile(); navigate('/dashboard', { replace: true }); } catch (requestError) { setError(requestError.response?.data?.message || requestError.message || 'Unable to complete onboarding.'); } finally { setSaving(false); } };
  const field = (name, label, type = 'text') => <Input id={name} name={name} label={label} type={type} value={profile[name]} onChange={(event) => updateDraft(name, event.target.value)} required />;
  if (loading) return <main className="grid min-h-[60vh] place-items-center"><p className="text-sm text-slate-500">Loading your onboarding progress...</p></main>;
  return <main className="mx-auto max-w-2xl px-4 py-10"><SectionCard><ProgressBar currentStep={step} totalSteps={5} label={titles[step - 1]} /><h1 className="mt-8 text-2xl font-bold">{titles[step - 1]}</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Set up your MentorLoop workspace.</p>{error && <p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700 dark:bg-red-500/10 dark:text-red-300">{error}</p>}<div className="mt-6 space-y-5">{step === 1 && <>{field('fullName', 'Full name')}{field('bio', 'Short bio')} {field('college', 'College')} {field('graduationYear', 'Graduation year', 'number')}</>}{step === 2 && <>{field('targetRole', 'Target role')}<label className="block text-sm font-medium">Experience level<select className="mt-1.5 w-full rounded-lg border border-slate-300 bg-white p-2.5 dark:border-slate-700 dark:bg-slate-900" value={profile.experienceLevel} onChange={(event) => updateDraft('experienceLevel', event.target.value)}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label></>}{step === 3 && <SkillSelector selectedSkills={skills} onChange={setSkills} />}{step === 4 && <><label className="block text-sm font-medium">Preferred learning style<select className="mt-1.5 w-full rounded-lg border border-slate-300 bg-white p-2.5 dark:border-slate-700 dark:bg-slate-900" value={profile.preferredLearningStyle} onChange={(event) => updateDraft('preferredLearningStyle', event.target.value)}><option value="visual">Visual</option><option value="reading-writing">Reading & writing</option><option value="hands-on">Hands-on</option><option value="mixed">Mixed</option></select></label>{field('dailyLearningGoal', 'Daily learning goal (minutes)', 'number')}</>}{step === 5 && <div className="space-y-3 text-sm"><p><b>Role:</b> {profile.targetRole}</p><p><b>Skills:</b> {skills.map((skill) => skill.skillName).join(', ')}</p><p><b>Daily goal:</b> {profile.dailyLearningGoal} minutes</p></div>}</div><div className="mt-8 flex justify-between gap-3">{step > 1 ? <button type="button" onClick={() => setStep((value) => value - 1)} className="rounded-lg px-4 py-2 font-semibold text-slate-600 dark:text-slate-300">Back</button> : <span />}{step < 5 ? <PrimaryButton onClick={next}>Continue</PrimaryButton> : <PrimaryButton onClick={submit} isLoading={saving}>Complete setup</PrimaryButton>}</div></SectionCard></main>;
};

const OnboardingPage = () => <OnboardingProvider><Wizard /></OnboardingProvider>;
export default OnboardingPage;
